import { FormEvent, useEffect, useState } from 'react'
import { skillsForLanguage } from './skillCollection'

type Health = 'checking' | 'online' | 'offline'
type Project = { id: number; name: string; slug: string; status: string; repoUrl: string; githubRepoId?: number; githubFullName?: string }
type Task = { id: number; title: string; status: string; priority: string }
type Note = { id: number; title: string; body: string }
type Activity = { id: string; type: string; repo: string; summary: string; createdAt: string }
type Repo = { id: number; name: string; fullName: string; description: string; url: string; private: boolean; language?: string; stars: number; updatedAt: string }
type User = { login: string; avatar_url?: string; name?: string }
type GitHubStats = { from: string; to: string; commits: number; pullRequests: number; issues: number; repositories: number }
type LanguageCollection = { name: string; count: number; projects: string[] }

const DEMO = import.meta.env.VITE_DEMO === 'true'
const demoProjects: Project[] = [{ id: 1, name: 'Trustyon', slug: 'trustyon', status: 'active', repoUrl: 'https://github.com/daikiito-dk/trustyon' }, { id: 2, name: 'Ghost Protocol', slug: 'ghost-protocol', status: 'active', repoUrl: '' }, { id: 3, name: 'Midnight Dungeon', slug: 'midnight-dungeon', status: 'active', repoUrl: '' }]
const demoTasks: Task[] = [{ id: 1, title: 'Trustyon API設計', status: 'todo', priority: 'high' }, { id: 2, title: 'Go middlewareを書く', status: 'todo', priority: 'medium' }, { id: 3, title: 'PostgreSQL migration', status: 'done', priority: 'medium' }, { id: 4, title: 'React Dashboard作成', status: 'todo', priority: 'high' }]
const demoNotes: Note[] = [{ id: 1, title: 'Trustyon MVP ideas', body: '' }, { id: 2, title: 'GitHub integration', body: '' }]
const demoActivities: Activity[] = [{ id: '1', type: 'PushEvent', repo: 'daikiito-dk/trustyon', summary: 'feat: add GitHub statistics', createdAt: new Date(Date.now() - 30 * 60000).toISOString() }, { id: '2', type: 'PushEvent', repo: 'daikiito-dk/Ghost-Protocol', summary: 'fix: enemy AI', createdAt: new Date(Date.now() - 90 * 60000).toISOString() }, { id: '3', type: 'PushEvent', repo: 'daikiito-dk/Midnight-Dungeon', summary: 'feat: inventory system', createdAt: new Date(Date.now() - 180 * 60000).toISOString() }]
const demoRepos: Repo[] = [{ id: 1, name: 'trustyon', fullName: 'daikiito-dk/trustyon', description: 'Personal Developer Operating System', url: 'https://github.com/daikiito-dk/trustyon', private: false, language: 'TypeScript', stars: 0, updatedAt: new Date().toISOString() }, { id: 2, name: 'Ghost-Protocol', fullName: 'daikiito-dk/Ghost-Protocol', description: 'Browser game prototype', url: 'https://github.com/daikiito-dk/Ghost-Protocol', private: false, language: 'TypeScript', stars: 0, updatedAt: new Date().toISOString() }]
const demoStats: GitHubStats = { from: new Date(Date.now() - 7 * 86400000).toISOString(), to: new Date().toISOString(), commits: 18, pullRequests: 3, issues: 5, repositories: 7 }

async function getJSON<T>(path: string, options?: RequestInit): Promise<T> { const response = await fetch(path, options); if (!response.ok) throw new Error(`API ${response.status}`); if (response.status === 204) return undefined as T; return response.json() }
function formatTime(value: string) { return new Date(value).toLocaleString('ja-JP', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) }
function languageCollection(repos: Repo[]): LanguageCollection[] { const groups = new Map<string, LanguageCollection>(); for (const repo of repos) { const name = repo.language?.trim(); if (!name) continue; const current = groups.get(name) ?? { name, count: 0, projects: [] }; current.count += 1; if (!current.projects.includes(repo.name)) current.projects.push(repo.name); groups.set(name, current) } return [...groups.values()].sort((a, b) => b.count - a.count || a.name.localeCompare(b.name)) }
function languageMark(name: string) { const marks: Record<string, string> = { TypeScript: 'TS', JavaScript: 'JS', Go: 'GO', Rust: 'RS', Python: 'PY', Java: 'JV', 'C#': 'C#', 'C++': 'C++', PHP: 'PHP', Ruby: 'RB', Swift: 'SW', Kotlin: 'KT' }; return marks[name] ?? name.slice(0, 2).toUpperCase() }

function App() {
  const [health, setHealth] = useState<Health>('checking'); const [user, setUser] = useState<User | null>(DEMO ? { login: 'demo-user', name: 'Demo User' } : null); const [projects, setProjects] = useState<Project[]>([]); const [tasks, setTasks] = useState<Task[]>([]); const [notes, setNotes] = useState<Note[]>([]); const [activities, setActivities] = useState<Activity[]>([]); const [repos, setRepos] = useState<Repo[]>([]); const [stats, setStats] = useState<GitHubStats | null>(null); const [loading, setLoading] = useState(true); const [syncing, setSyncing] = useState(false); const [newTask, setNewTask] = useState(''); const [priority, setPriority] = useState('medium'); const [newProject, setNewProject] = useState(''); const [newNote, setNewNote] = useState(''); const [saving, setSaving] = useState(false); const [selectedLanguage, setSelectedLanguage] = useState<string | null>(null)
  const load = async () => { if (DEMO) { setProjects(demoProjects); setTasks(demoTasks); setNotes(demoNotes); setActivities(demoActivities); setRepos(demoRepos); setStats(demoStats); setHealth('online'); return } const [projectData, taskData, noteData, activityData, repoData, userData] = await Promise.all([getJSON<Project[]>('/api/projects'), getJSON<Task[]>('/api/tasks'), getJSON<Note[]>('/api/notes'), getJSON<Activity[]>('/api/github/activity'), getJSON<Repo[]>('/api/github/repos').catch(() => []), getJSON<User>('/api/auth/me').catch(() => null)]); setProjects(projectData); setTasks(taskData); setNotes(noteData); setActivities(activityData); setRepos(repoData); setUser(userData); if (userData) setStats(await getJSON<GitHubStats>('/api/github/stats').catch(() => null)); setHealth('online') }
  useEffect(() => { load().catch(() => setHealth('offline')).finally(() => setLoading(false)) }, [])
  const syncGitHub = async () => { if (!user || syncing || DEMO) return; setSyncing(true); try { const synced = await getJSON<Project[]>('/api/github/sync', { method: 'POST' }); setProjects(synced); const refreshedRepos = await getJSON<Repo[]>('/api/github/repos').catch(() => []); setRepos(refreshedRepos); setStats(await getJSON<GitHubStats>('/api/github/stats').catch(() => null)); setHealth('online') } catch { setHealth('offline') } finally { setSyncing(false) } }
  const addTask = async (event: FormEvent) => { event.preventDefault(); const title = newTask.trim(); if (!title || saving) return; if (DEMO) { setTasks((current) => [{ id: Date.now(), title, status: 'todo', priority }, ...current]); setNewTask(''); return } setSaving(true); try { const task = await getJSON<Task>('/api/tasks', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, status: 'todo', priority }) }); setTasks((current) => [task, ...current]); setNewTask(''); setHealth('online') } catch { setHealth('offline') } finally { setSaving(false) } }
  const addProject = async (event: FormEvent) => { event.preventDefault(); const name = newProject.trim(); if (!name || saving) return; if (DEMO) { setProjects((current) => [{ id: Date.now(), name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'), status: 'active', repoUrl: '' }, ...current]); setNewProject(''); return } setSaving(true); try { const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || `project-${Date.now()}`; const project = await getJSON<Project>('/api/projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, slug, status: 'active' }) }); setProjects((current) => [project, ...current]); setNewProject(''); setHealth('online') } catch { setHealth('offline') } finally { setSaving(false) } }
  const addNote = async (event: FormEvent) => { event.preventDefault(); const title = newNote.trim(); if (!title || saving) return; if (DEMO) { setNotes((current) => [{ id: Date.now(), title, body: '' }, ...current]); setNewNote(''); return } setSaving(true); try { const note = await getJSON<Note>('/api/notes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, body: '' }) }); setNotes((current) => [note, ...current]); setNewNote(''); setHealth('online') } catch { setHealth('offline') } finally { setSaving(false) } }
  const toggleTask = async (task: Task) => { const status = task.status === 'done' ? 'todo' : 'done'; if (DEMO) { setTasks((current) => current.map((item) => item.id === task.id ? { ...item, status } : item)); return } try { const updated = await getJSON<Task>(`/api/tasks/${task.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...task, status }) }); setTasks((current) => current.map((item) => item.id === updated.id ? updated : item)) } catch { setHealth('offline') } }
  const deleteTask = async (id: number) => { if (DEMO) { setTasks((current) => current.filter((task) => task.id !== id)); return } try { await getJSON<void>(`/api/tasks/${id}`, { method: 'DELETE' }); setTasks((current) => current.filter((task) => task.id !== id)) } catch { setHealth('offline') } }
  const logout = async () => { if (!DEMO) await fetch('/api/auth/logout', { method: 'POST' }); setUser(null); setRepos([]); setStats(null); setSelectedLanguage(null) }
  const openTasks = tasks.filter((task) => task.status !== 'done').slice(0, 5); const doneTasks = tasks.filter((task) => task.status === 'done').slice(0, 3); const languages = languageCollection(repos); const selected = selectedLanguage ? languages.find((language) => language.name === selectedLanguage) : null; const selectedLevel = selected ? Math.min(5, selected.count + 1) : 0; const selectedSkills = selected ? skillsForLanguage(selected.name, selectedLevel) : []
  return <main className="shell">
    <header className="header"><div><span className="eyebrow">PERSONAL DEVELOPER OS</span><h1>Trustyon</h1></div><div className="header-actions">{user ? <><button className="sync-button" onClick={syncGitHub} disabled={syncing || DEMO}>{DEMO ? 'Demo mode' : syncing ? 'Syncing…' : 'Sync GitHub'}</button><button className="account" onClick={logout}>{user.avatar_url && <img src={user.avatar_url} alt="" />} @{user.login} · {DEMO ? 'Reset' : 'Sign out'}</button></> : <a className="github-login" href="/api/auth/github/login">Connect GitHub</a>}<div className={`status ${health}`}><span /> {DEMO ? 'Demo' : 'API'} {health}</div></div></header>
    <section className="hero"><div className="hero-label"><p className="eyebrow">TODAY</p>{DEMO && <span className="demo-badge">DEMO</span>}</div><h2>Build. Learn. Ship.</h2><p className="muted">Your development history, projects, tasks, and notes — in one place.</p></section>
    {user && <section className="stats-grid">{[['Commits', stats?.commits, 'last 7 days'], ['Pull requests', stats?.pullRequests, 'last 7 days'], ['Issues', stats?.issues, 'last 7 days'], ['Repositories', stats?.repositories, 'accessible total']].map(([label, value, hint]) => <article className="stat-card" key={label as string}><span className="eyebrow">{label as string}</span><strong>{loading ? '—' : value ?? '—'}</strong><small>{hint as string}</small></article>)}</section>}
    <section className="collection-section"><div className="section-heading"><div><p className="eyebrow">YOUR COLLECTION</p><h3>Languages</h3></div><span>{languages.length} collected</span></div>{languages.length > 0 ? <div className="language-grid">{languages.map((language) => { const level = Math.min(5, language.count + 1); const unlocked = skillsForLanguage(language.name, level); return <article className={`language-card ${selectedLanguage === language.name ? 'selected' : ''}`} key={language.name} onClick={() => setSelectedLanguage(language.name)} role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') setSelectedLanguage(language.name) }}><div className="language-icon">{languageMark(language.name)}</div><div className="language-info"><strong>{language.name}</strong><span>{language.count} {language.count === 1 ? 'repository' : 'repositories'} · {unlocked.length}/5 skills</span><small>{unlocked.slice(0, 2).map((skill) => skill.name).join(' · ') || 'Foundation locked'}</small></div><div className="language-level">LV.{level}</div></article> })}</div> : <div className="collection-empty"><span className="empty-icon">＋</span><div><strong>Your first language is waiting</strong><p>Connect GitHub and start collecting the technologies you build with.</p></div></div>}{selected && <div className="skill-panel"><div className="skill-panel-head"><div><p className="eyebrow">LANGUAGE UNLOCK</p><h4>{selected.name} · LV.{selectedLevel}</h4><span>{selectedSkills.length}/5 skills unlocked</span></div><button className="skill-close" onClick={() => setSelectedLanguage(null)} aria-label="Close skill panel">×</button></div><div className="skill-list">{(skillsForLanguage(selected.name, 5)).map((skill) => <div className={`skill-item ${skill.unlockAt <= selectedLevel ? 'unlocked' : 'locked'}`} key={skill.name}><span>{skill.unlockAt <= selectedLevel ? '✓' : '○'}</span><div><strong>{skill.name}</strong><small>{skill.description}</small></div><em>LV.{skill.unlockAt}</em></div>)}</div></div>}</section>
    <section className="grid">
      <article className="card wide"><div className="card-title"><span>Tasks</span><strong>{loading ? '—' : tasks.length}</strong></div><form className="task-form" onSubmit={addTask}><input value={newTask} onChange={(event) => setNewTask(event.target.value)} placeholder="What needs to ship?" aria-label="New task" /><select value={priority} onChange={(event) => setPriority(event.target.value)} aria-label="Priority"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select><button type="submit" disabled={saving || !newTask.trim()}>Add task</button></form>{openTasks.length > 0 ? <ul className="task-list">{openTasks.map((task) => <li key={task.id}><button className="check" onClick={() => toggleTask(task)} aria-label={`Complete ${task.title}`}>□</button><span className="task-name">{task.title}</span><small>{task.priority}</small><button className="delete" onClick={() => deleteTask(task.id)} aria-label={`Delete ${task.title}`}>×</button></li>)}</ul> : <p className="muted">{loading ? 'Loading tasks…' : 'No open tasks. Add your next move above.'}</p>}{doneTasks.length > 0 && <div className="completed"><p className="eyebrow">COMPLETED</p>{doneTasks.map((task) => <div className="completed-task" key={task.id}><button className="check" onClick={() => toggleTask(task)}>✓</button><span>{task.title}</span><button className="delete" onClick={() => deleteTask(task.id)}>×</button></div>)}</div>}</article>
      <article className="card"><div className="card-title"><span>Projects</span><strong>{loading ? '—' : projects.length}</strong></div><form className="mini-form" onSubmit={addProject}><input value={newProject} onChange={(event) => setNewProject(event.target.value)} placeholder="New project" aria-label="New project" /><button type="submit" disabled={saving || !newProject.trim()}>+</button></form>{projects.length > 0 ? <ul className="simple-list">{projects.slice(0, 5).map((project) => <li key={project.id}><span>{project.githubRepoId ? '↗' : '●'}</span>{project.name}</li>)}</ul> : <p className="muted">{loading ? 'Loading projects…' : 'No projects yet.'}</p>}</article>
      <article className="card"><div className="card-title"><span>Notes</span><strong>{loading ? '—' : notes.length}</strong></div><form className="mini-form" onSubmit={addNote}><input value={newNote} onChange={(event) => setNewNote(event.target.value)} placeholder="New note" aria-label="New note" /><button type="submit" disabled={saving || !newNote.trim()}>+</button></form>{notes.length > 0 ? <ul className="simple-list">{notes.slice(0, 5).map((note) => <li key={note.id}><span>↳</span>{note.title}</li>)}</ul> : <p className="muted">{loading ? 'Loading notes…' : 'Capture ideas and technical notes.'}</p>}</article>
      <article className="card wide activity-card"><div className="card-title"><span>GitHub Activity</span><strong>{loading ? '—' : activities.length}</strong></div>{activities.length > 0 ? <ul className="activity-list">{activities.slice(0, 8).map((activity) => <li key={activity.id}><time>{formatTime(activity.createdAt)}</time><div><b>{activity.repo}</b><span>{activity.summary}</span></div></li>)}</ul> : <p className="muted">{loading ? 'Loading GitHub activity…' : 'No GitHub activity found.'}</p>}</article>
      <article className="card wide"><div className="card-title"><span>GitHub Repositories</span><strong>{loading ? '—' : repos.length}</strong></div>{repos.length > 0 ? <ul className="repo-list">{repos.slice(0, 8).map((repo) => <li key={repo.id}><div><a href={repo.url} target="_blank" rel="noreferrer"><b>{repo.fullName}</b></a><span>{repo.description || 'No description'}</span></div><small>{repo.private ? 'Private' : 'Public'}{repo.language ? ` · ${repo.language}` : ''} · ★ {repo.stars}</small></li>)}</ul> : <p className="muted">{user ? 'No repositories found.' : 'Connect GitHub to sync your repositories.'}</p>}</article>
    </section>
  </main>
}
export default App
